name: Terraform AWS Workflow

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: eu-central-1

      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Install Python and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install -r requirements.txt

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.5

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
            echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs -n 1 dirname | grep -v '^\.' | head -1 | sort -u)" >> $GITHUB_ENV
          else
            echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs -n 1 dirname | grep -v '^\.' | sort -u)" >> $GITHUB_ENV
          fi

      - name: Set Terraform Environment
        run: |
          changed_files="${{ steps.changed-files.outputs.changed_files }}"
          dir=${{ env.changed_files }}
          echo "Chosen env: $dir"

      - name: Terraform init and validate
        run: |
          echo " Running Terraform Init & Validate "
          terraform init
          terraform validate
        working-directory: ${{ env.changed_files }}

      - name: Terraform plan and apply
        run: |
          terraform plan
          terraform apply -auto-approve
        working-directory: ${{ env.changed_files }}

      - name: Run AWS Tests
        run: |
          echo " Running AWS Tests "
          python3 tests/aws_tests.py

      - name: Terraform Destroy
        run: |
          echo " Running Terraform Destroy "
          terraform destroy -auto-approve
        working-directory: ${{ env.changed_files }}
