name: Terraform AWS Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
        aws-region: eu-central-1

    - name: Install Python and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install -r ../requirements.txt

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.2

    - name: Terraform init and validate
      run: |
        echo " Running Terraform Init & Validate "
        terraform init
        terraform validate
        
    - name: Terraform plan and apply
      run: |
        terraform plan
        terraform apply -auto-approve

    - name: Run AWS Tests
      run: |
        echo " Running AWS Tests "
        python3 tests/aws_tests.py

    - name: Terraform Destroy
      run: |
        echo " Running Terraform Destroy "
        terraform destroy -auto-approve
